name: Java Build & Deployment - DoX-CLI Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  cicd:
    runs-on: dox-runner-set
    env:
      JDK_VERSION: 17

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Maven Build
        run: dox maven build

      - name: Docker Build & Push
        run: dox docker build push

      - name: GitOps Deploy
        run: dox gitops update-image-tag

